name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: driveconstructor-staging/driveconstructor-staging.github.io
          token: ${{ secrets.GH_PAT }}
          path: out
      - name: Commit files
        run: |
          cd out
          git config --local user.email "build.bot@driveconstructor.com"
          git config --local user.name "Build Bot"
          echo $(date) >> index.html
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          directory: out
          repository: driveconstructor-staging/driveconstructor-staging.github.io
          force: true   
